logging.level.com.example.demo: debug
logging.file: ./log/local


server:
  port: 8097
  
spring.jpa:
  hibernate.ddl-auto: none
  show-sql: true
  properties.hibernate.format_sql : true

spring.datasource:
  url: jdbc:h2:tcp://localhost/~/test
  driverClassName: org.h2.Driver
  username: sa
  password:

spring.mvc.view:
  prefix: /
  suffix: .jsp

spring.security.user:
  name: root
  password: wonchul

